METADATA_DIR = "metadata"

CORPUS_DIR = f"{METADATA_DIR}/corpus"
CORPUS_DATA_DIR = f"{CORPUS_DIR}/data"
CORPUS_NLTK_DICTIONARY_DIR = f"{CORPUS_DIR}/nltk/dictionary"

EMBEDDINGS_DIR = f"{METADATA_DIR}/embeddings"
EMBEDDINGS_PRETRAINED_GLOVE_PATH = f"{EMBEDDINGS_DIR}/glove.6B.300d.txt"

MODEL_DIR = f"{METADATA_DIR}/model"
MODEL_ARTIFACTS_DIR = f"{MODEL_DIR}/artifacts"
MODEL_REPOSITORY_DIR = f"{MODEL_DIR}/repository"

TENSORBOARD_DIR = f"{METADATA_DIR}/runs"
