METADATA_DIR = "metadata"

CORPUS_DIR = f"{METADATA_DIR}/corpus"
CORPUS_DATA_DIR = f"{CORPUS_DIR}/data"
CORPUS_NLTK_DICTIONARY_DIR = f"{CORPUS_DIR}/nltk/dictionary"

MODEL_DIR = f"{METADATA_DIR}/model"
MODEL_ARCHIVE_DIR = f"{MODEL_DIR}/archive"
MODEL_REPOSITORY_DIR = f"{MODEL_DIR}/repository"

TENSORBOARD_DIR = f"{METADATA_DIR}/runs"
